export const ADD_ACCOMPLISHMENTS = 'Add another Accomplishments'
export const ADD_CERTIFICATION = 'Add another Certification'
export const ADD_EDUCATION = 'Add another Education'
export const ADD_EXPERIENCE = 'Add another Experience'
export const ADD_ROTATION = 'Add another Rotation'
export const SEND_REQUEST = 'Send Request'
export const SELECT_FILE = 'Select File'
